# --------------------------------------------------------------------------------------------------
# Copyright (c) Andreas Gustavsson. All rights reserved.
#
# This file is part of the hdl-registers project, an HDL register generator fast enough to run
# in real time.
# https://hdl-registers.com
# https://github.com/hdl-registers/hdl-registers
# --------------------------------------------------------------------------------------------------

from pathlib import Path
from typing import Any

from hdl_registers.field.bit import Bit
from hdl_registers.field.bit_vector import BitVector
from hdl_registers.field.enumeration import Enumeration
from hdl_registers.field.integer import Integer
from hdl_registers.field.numerical_interpretation import (Signed,
                                                          SignedFixedPoint,
                                                          Unsigned,
                                                          UnsignedFixedPoint)
from hdl_registers.register_list import RegisterList

from .rust_common import RustGeneratorCommon


class RustFlatGenerator(RustGeneratorCommon):
    """
    Generate a flat Rust interface for an hdl-registers register list.

    The interface expects the user to implement an accessor trait,
    specifying how to actually access the registers (or mock that access).
    """

    COMMENT_START = "//"
    SHORT_DESCRIPTION = "Rust (flat)"

    def __init__(
        self,
        register_list: RegisterList,
        output_folder: Path,
        file_name: str | None = None,
    ) -> None:
        super().__init__(register_list=register_list, output_folder=output_folder)
        self._file_name = f"{self.name}_flat.rs" if file_name is None else file_name
        self._struct_name = self._struct_name + "Flat"
        # self._constants_prefix += "_FLAT"

    @property
    def output_file(self) -> Path:
        """
        Result of `get_code()` is placed in this file.
        """
        return self.output_folder / self._file_name

    def get_code(self, **kwargs: Any) -> str:
        """
        Get complete Rust code with declared constant, enums, and a struct representing
        the register file, with trait-based register access.
        """
        consts_code = self._get_constants_mod()
        enums_code = self._get_enums_mod()
        regfile_code = self._get_register_file_code_block()
        empty = not (consts_code or enums_code or regfile_code)
        only_consts = consts_code and not (enums_code or regfile_code)
        if empty:
            return ""
        elif only_consts:
            return self._get_common_header() + consts_code
        else:
            rust_code = []
            rust_code.append(self._get_common_header())
            rust_code.append(f"""\
//! Generated by {self.__class__.__name__} from HDL-registers.
//! 
//! Example dummy usage (a production-ready implementation would likely use
//! `read_volatile` and `write_volatile` on mapped memory), based on a register
//! file generated from {self.name}.toml using the {self.__class__.__name__}:
//!
//! ```
//! mod {self.name}_flat;
//!
//! use {self.name}_flat::*;
//! use std::cell::RefCell;
//! use std::rc::Rc;
//!
//! #[derive(Clone)]
//! pub struct RegAcc {{
//!     regs: Rc<RefCell<[u32; 4096]>>,
//! }}
//!
//! impl {self._struct_name}Accessor for RegAcc {{
//!     fn read32(&self, offset: usize) -> Result<u32, &'static str> {{
//!         assert!(
//!             offset.is_multiple_of(4),
//!             "Read offset {{}} is not 4-byte aligned",
//!             offset
//!         );
//!         Ok(self.regs.borrow()[offset / 4])
//!     }}
//!
//!     fn write32(&mut self, offset: usize, val: u32) -> Result<(), &'static str> {{
//!         assert!(
//!             offset.is_multiple_of(4),
//!             "Write offset {{}} is not 4-byte aligned",
//!             offset
//!         );
//!         self.regs.borrow_mut()[offset / 4] = val;
//!         Ok(())
//!     }}
//! }}
//!
//! fn main() {{
//!     // Initialize shared mock memory and the register interface
//!     let memory = Rc::new(RefCell::new([0; 4096]));
//!     let reg_acc = RegAcc {{
//!         regs: Rc::clone(&memory),
//!     }};
//!     let mut regs = {self._struct_name}::new(reg_acc);
//!     // Access whatever registers are defined, such as:
//!     // let status = regs.read_status();
//!     // regs.write_control(42);
//! }}
//! ```

""")
            rust_code.append(self._get_trait())
            rust_code.append(self._newline())
            if consts_code:
                rust_code.append(consts_code)
                rust_code.append(self._newline())
            if enums_code:
                rust_code.append(enums_code)
                rust_code.append(self._newline())
            rust_code.append(regfile_code)
            return "".join(rust_code)

    def _get_register_file_code_block(self) -> str:
        """
        Returns a code block representing the accessible registers file.
        """
        ind = self._get_indentation(1)
        struct_impl_content: [str] = []
        for register, register_array in self.iterate_registers():
            struct_impl_content.append(
                self._get_register_methods(register, register_array)
            )
        struct_impl_content = "".join(struct_impl_content)
        if struct_impl_content:
            return f"""\
{self._get_comment_header("Register File")}

#[derive(Clone, Copy, Debug)]
pub struct {self._struct_name}<A: {self._struct_name}Accessor> {{
{ind}accessor: A,
}}
{self._within_struct_impl(struct_impl_content)}"""
        else:
            return ""

    def _within_struct_impl(self, content: str) -> str:
        """
        Returns the definition of the struct representing the register file and
        puts the provided code for read and write functions inside the implementation
        for that struct.
        """
        ind = self._get_indentation(1)
        if content:
            return f"""\
impl<A: {self._struct_name}Accessor> {self._struct_name}<A> {{
{ind}/// Construct a new register accessor.
{ind}/// # Safety
{ind}/// The caller must ensure that the accessor is safe.
{ind}pub const fn new(accessor: A) -> Self {{
{ind}{ind}Self {{ accessor }}
{ind}}}
{content}\
{self._get_helper_functions(1)}\
}}
"""
        return ""

    def _get_float_from_fixedpoint(
        self, value_str: str, is_signed: bool, min_bit_index: int
    ) -> float:
        """
        Creates and returns a floating-point number from a bit string.
        """
        assert value_str, "Bit string of length 0 cannot be translated into float"
        num_fractional_bits = abs(min_bit_index)
        sign = -1 if is_signed else 1
        bit_sum = 0
        bit_val = 1
        for c in reversed(value_str[1:]):
            val = ord(c) - 0x30
            assert val == 0 or val == 1, "Invalid bit string"
            bit_sum += bit_val * val
            bit_val *= 2
        bit_sum += bit_val * (sign * (ord(value_str[0]) - 0x30))
        val = float(bit_sum) / 2**num_fractional_bits
        return val

    def _get_int_from_bits(self, value_str: str, is_signed: bool) -> int:
        """
        Creates and returns an integer from a bit string.
        """
        assert value_str, "Bit string of length 0 cannot be translated into int"
        assert value_str[0] == "0" or value_str[0] == "1", "Invalid bit string"
        is_negative = is_signed and value_str[0] == "1"
        bit_sum = 0
        bit_val = 1
        for c in reversed(value_str[1:]):
            val = ord(c) - 0x30
            assert val == 0 or val == 1, "Invalid bit string"
            if is_negative:
                val = 1 - val
            bit_sum += bit_val * val
            bit_val *= 2
        if not is_signed:
            bit_sum += bit_val * (ord(value_str[0]) - 0x30)
        return bit_sum

    def _get_register_methods(
        self, register: Any, register_array: Any, base_ind_lev: int = 1
    ) -> str:
        """
        Returns the getters and setters for a single register
        """

        mode_str = (
            register.mode.name if hasattr(register.mode, "name") else str(register.mode)
        )

        # Indentation
        base_ind = self._get_indentation(base_ind_lev)
        ind = self._get_indentation(1)

        # Resolve Addressing
        if register_array is None:
            reg_array_txt = ""
            reg_name = register.name
            array_index_param = ""
            array_index_param_set = ""
            array_index_comment = ""
            array_args = ""
            offset_expr = f"0x{register.index * 4:X}"
            array_check = ""
        else:
            reg_array_txt = f" Array (length: {register_array.length})"
            reg_name = f"{register_array.name}_{register.name}"
            array_index_param = "array_index"
            array_index_param_set = f"{array_index_param}, "
            array_index_comment = f" with index `{array_index_param}`"
            array_args = f", {array_index_param}: usize"
            array_len = len(register_array.registers)
            array_base = register_array.base_index + register.index
            if array_base == 0:
                offset_expr = f"{array_index_param} * 0x{array_len * 4:X}"
            else:
                offset_expr = f"\
0x{array_base * 4:X} + {array_index_param} * 0x{array_len * 4:X}"
            array_check = f"""\
{base_ind}{ind}if {array_index_param} >= {register_array.length} {{
{base_ind}{ind}{ind}return Err("{array_index_param} is larger than {register_array.length - 1}");
{base_ind}{ind}}}
"""
        # Register description
        register_description = ""
        if register.description:
            register_description = f"""

Description:
{register.description}"""

        # Generate methods
        is_read = register.mode.software_can_read
        is_write = register.mode.software_can_write
        reg_var = "reg_val"
        reg_default_value: int = 0
        fields_code: list[str] = []
        for field in register.fields:
            field_var = "field_val"
            field_name = field.name
            field_description = ""
            if field.description:
                field_description = f"""

{ind}Description:
{ind}{field.description.replace("\n", f"\n{ind}")}"""

            # Field window
            shift = field.base_index
            mask = (1 << field.width) - 1
            reg_default_value += field.default_value_uint << shift

            # Field type
            is_bit = isinstance(field, Bit)
            is_enum = isinstance(field, Enumeration)
            is_int = isinstance(field, Integer)
            is_sint = is_int and field.is_signed
            is_uint = is_int and not field.is_signed
            is_bit_vector = isinstance(field, BitVector)
            is_bit_vector_sint = is_bit_vector and isinstance(
                field.numerical_interpretation, Signed
            )
            is_bit_vector_uint = is_bit_vector and isinstance(
                field.numerical_interpretation, Unsigned
            )
            is_bit_vector_int = is_bit_vector_sint or is_bit_vector_uint
            is_bit_vector_sfixed = is_bit_vector and isinstance(
                field.numerical_interpretation, SignedFixedPoint
            )
            is_bit_vector_ufixed = is_bit_vector and isinstance(
                field.numerical_interpretation, UnsignedFixedPoint
            )
            is_bit_vector_fixed = is_bit_vector_sfixed or is_bit_vector_ufixed

            # Derive min and max limits for field 1
            if is_sint or is_bit_vector_sint:
                field_min = -(1 << (field.width - 1))
                field_max = (1 << (field.width - 1)) - 1
            elif is_bit_vector_sfixed:
                f = abs(field.numerical_interpretation.min_bit_index)
                field_min = self._get_float_from_fixedpoint(
                    "1" + (field.width - 1) * "0", True, f
                )
                field_max = self._get_float_from_fixedpoint(
                    "0" + (field.width - 1) * "1", True, f
                )
            elif is_bit_vector_ufixed:
                f = abs(field.numerical_interpretation.min_bit_index)
                field_min = self._get_float_from_fixedpoint(field.width * "0", False, f)
                field_max = self._get_float_from_fixedpoint(field.width * "1", False, f)
            else:  # bit, enum, uint, bv_uint, u32
                field_min = 0
                field_max = (1 << field.width) - 1

            # Derive user-specified min and max limits
            if is_enum:
                val_min = 0
                val_max = len(field.elements) - 1
            elif is_int:
                val_min = field.min_value
                val_max = field.max_value
            elif is_bit_vector:
                val_min = field.numerical_interpretation.min_value
                val_max = field.numerical_interpretation.max_value
            else:  # bit, u32
                val_min = field_min
                val_max = field_max

            # Derive field type and default value
            if is_bit:
                field_type = "bool"
                field_default_value = (
                    "true" if field.default_value_uint != 0 else "false"
                )
            elif is_enum:
                field_type = (
                    f"enums::{self._get_enum_name(register, register_array, field)}"
                )
                field_default_value = (
                    f"{field_type}::from_u32({field.default_value_uint})"
                )
            elif is_sint:
                field_type = "i32"
                field_default_value = field.default_value
            elif is_bit_vector_sint:
                field_type = "i32"
                field_default_value = self._get_int_from_bits(field.default_value, True)
            elif is_uint or is_bit_vector_uint:
                field_type = "u32"
                field_default_value = field.default_value_uint
            elif is_bit_vector_sfixed or is_bit_vector_ufixed:
                self._found_f64_get_field |= is_read
                self._found_f64_set_field |= is_write
                field_type = "f64"
                signed = is_bit_vector_sfixed
                f = abs(field.numerical_interpretation.min_bit_index)
                field_default_value = self._get_float_from_fixedpoint(
                    field.default_value, signed, f
                )
            else:
                raise ValueError(
                    f"BUG: Cannot derive field type and default value for {field}"
                )

            # Derive value assertions
            assert_max = val_max < field_max
            assert_min = field_min < val_min
            value_assert_min_get = f"""\
{base_ind}{ind}if {field_var} < {val_min} {{
{base_ind}{ind}{ind}return Err("Read value is smaller than {val_min}");
{base_ind}{ind}}}
"""
            value_assert_max_get = f"""\
{base_ind}{ind}if {val_max} < {field_var} {{
{base_ind}{ind}{ind}return Err("Read value is larger than {val_max}");
{base_ind}{ind}}}
"""
            value_assert_min_set = f"""\
{base_ind}{ind}if {field_var} < {val_min} {{
{base_ind}{ind}{ind}return Err("{field_var} cannot be smaller than {val_min}");
{base_ind}{ind}}}
"""
            value_assert_max_set = f"""\
{base_ind}{ind}if {val_max} < {field_var} {{
{base_ind}{ind}{ind}return Err("{field_var} cannot be larger than {val_max}");
{base_ind}{ind}}}
"""

            # Derive field-extraction expression
            if shift == 0 and mask == 0xFFFF_FFFF:
                field_extraction = f"{reg_var}"
            elif shift == 0:
                field_extraction = f"{reg_var} & 0x{mask:X}"
            else:
                field_extraction = f"({reg_var} >> {shift}) & 0x{mask:X}"

            # Derive get_..._from() body
            if is_bit:
                get_from_body = f"{base_ind}{ind}Ok(({field_extraction}) != 0)"
            elif is_enum:
                get_from_body = f"""\
{base_ind}{ind}let {field_var} = {field_extraction};
"""
                if assert_min:
                    get_from_body += value_assert_min_get
                if assert_max:
                    get_from_body += value_assert_max_get
                get_from_body += f"""\
{base_ind}{ind}Ok({field_type}::from_u32({field_var}))"""
            elif is_sint or is_bit_vector_sint:
                if field.width == 32:
                    get_from_body = f"{base_ind}{ind}Ok(({field_extraction}) as i32)"
                else:
                    sign_bit = 1 << (field.width - 1)
                    get_from_body = f"""\
{base_ind}{ind}let mut {field_var} = ({field_extraction}) as i32;
{base_ind}{ind}// Sign-extend
{base_ind}{ind}if ({field_var} & 0x{sign_bit:X}) != 0 {{
{base_ind}{ind}{ind}{field_var} |= !(0x{mask:X});
{base_ind}{ind}}}
"""
                    if assert_min:
                        get_from_body += value_assert_min_get
                    if assert_max:
                        get_from_body += value_assert_max_get
                    get_from_body += f"""\
{base_ind}{ind}Ok({field_var})"""
            elif is_uint or is_bit_vector_uint:
                if not assert_min and not assert_max:
                    get_from_body = f"{base_ind}{ind}Ok({field_extraction})"
                else:
                    get_from_body = f"""\
{base_ind}{ind}let {field_var} = {field_extraction};
"""
                    if assert_min:
                        get_from_body += value_assert_min_get
                    if assert_max:
                        get_from_body += value_assert_max_get
                    get_from_body += f"""\
{base_ind}{ind}Ok({field_var})"""
            elif is_bit_vector_sfixed or is_bit_vector_ufixed:
                fracs = abs(field.numerical_interpretation.min_bit_index)
                signed = "true" if is_bit_vector_sfixed else "false"
                get_from_body = f"""\
{base_ind}{ind}let {field_var} = {field_extraction};
"""
                if not assert_min and not assert_max:
                    get_from_body += f"""\
{base_ind}{ind}Ok(Self::from_fixed_point_field({field_var}, {field.width}, {fracs}, {signed}))"""
                else:
                    get_from_body += f"""\
{base_ind}{ind}let {field_var} = Self::from_fixed_point_field({field_var}, {field.width}, {fracs}, {signed});
"""
                    if assert_min:
                        get_from_body += value_assert_min_get
                    if assert_max:
                        get_from_body += value_assert_max_get
                    get_from_body += f"""\
{base_ind}{ind}Ok({field_var})"""
            else:
                raise ValueError(f"BUG: Cannot derive body for get_..._from(): {field}")

            # Define field-insertion expression
            if field_type != "u32" and field_type != "f64":
                field_insertion_cast = f"({field_var} as u32)"
            else:
                field_insertion_cast = f"{field_var}"
            if shift == 0 and mask == 0xFFFF_FFFF:
                field_insertion = f"{field_insertion_cast}"
            elif shift == 0:
                field_insertion = f"\
({reg_var} & !0x{mask:X}) | ({field_insertion_cast} & 0x{mask:X})"
            else:
                field_insertion = f"\
({reg_var} & !(0x{mask:X} << {shift})) | (({field_insertion_cast} & 0x{mask:X}) << {shift})"

            # Derive set_..._in() body
            if is_bit:
                set_in_body = f"{base_ind}{ind}Ok({field_insertion})"
            elif is_enum:
                set_in_body = f"{base_ind}{ind}Ok({field_insertion})"
            elif is_int or is_bit_vector_int:
                set_in_body = ""
                if field.width < 32:
                    if assert_min or is_sint or is_bit_vector_sint:
                        set_in_body += value_assert_min_set
                    set_in_body += value_assert_max_set
                else:
                    if assert_min:
                        set_in_body += value_assert_min_set
                    if assert_max:
                        set_in_body += value_assert_max_set
                set_in_body += f"""\
{base_ind}{ind}Ok({field_insertion})"""
            elif is_bit_vector_sfixed or is_bit_vector_ufixed:
                fracs = abs(field.numerical_interpretation.min_bit_index)
                signed = "true" if is_bit_vector_sfixed else "false"
                set_in_body = value_assert_min_set
                set_in_body += value_assert_max_set
                set_in_body = f"""\
{value_assert_min_set}
{value_assert_max_set}
{base_ind}{ind}let {field_var} = Self::to_fixed_point_field({field_var}, {field.width}, {fracs}, {signed});
{base_ind}{ind}Ok({field_insertion})"""
            else:
                raise ValueError(f"BUG: Cannot derive body for set_..._in(): {field}")

            # Add methods to `fields_code`
            fields_code.append(
                self._get_comment_header_field(
                    f"{ind}Field `{reg_name}.{field_name}` ({mode_str})"
                    + field_description,
                    base_ind_lev,
                )
            )
            fields_code.append(self._newline())
            # Field default value
            fields_code.append(f"""
{base_ind}/// Returns the default value of the field.
{base_ind}pub fn get_{reg_name}_{field_name}_default(&self) -> {field_type} {{
{base_ind}{ind}{field_default_value}
{base_ind}}}
""")
            # Getters
            if is_read:
                # Getter of field from any u32
                fields_code.append(f"""
{base_ind}/// Returns the (down-shifted) value of the field as found in `{reg_var}`,
{base_ind}/// or an error description on failure.
{base_ind}pub fn get_{reg_name}_{field_name}_from(&self, {reg_var}: u32) -> Result<{field_type}, &'static str> {{
{get_from_body}
{base_ind}}}
""")
                # Read field from register
                fields_code.append(f"""
{base_ind}/// Reads the register{array_index_comment} and returns the (down-shifted) value of the field,
{base_ind}/// or an error description on failure.
{base_ind}pub fn read_{reg_name}_{field_name}(&self{array_args}) -> Result<{field_type}, &'static str> {{
{base_ind}{ind}let {reg_var} = self.read_{reg_name}({array_index_param})?;
{base_ind}{ind}self.get_{reg_name}_{field_name}_from({reg_var})
{base_ind}}}
""")
            # Setters
            if is_write:
                # Sets the field in any u32 and returns the result
                fields_code.append(f"""
{base_ind}/// Sets the specified value, `{field_var}`, at the field's location in `{reg_var}` and returns the result,
{base_ind}/// or an error description on failure.
{base_ind}pub fn set_{reg_name}_{field_name}_in(&mut self, {reg_var}: u32, {field_var}: {field_type}) -> Result<u32, &'static str> {{
{set_in_body}
{base_ind}}}
""")
                if self.field_setter_should_read_modify_write(register=register):
                    # Read-modify-write the register
                    fields_code.append(f"""
{base_ind}/// Reads the register{array_index_comment}, applies the field value, `{field_var}`, and writes the result to the register.
{base_ind}/// Returns an error description on failure.
{base_ind}pub fn write_{reg_name}_{field_name}(&mut self{array_args}, {field_var}: {field_type}) -> Result<(), &'static str> {{
{base_ind}{ind}let {reg_var} = self.read_{reg_name}({array_index_param})?;
{base_ind}{ind}let new_{reg_var} = self.set_{reg_name}_{field_name}_in({reg_var}, {field_var})?;
{base_ind}{ind}self.write_{reg_name}({array_index_param_set}new_{reg_var})
{base_ind}}}
""")
                else:
                    comment = f"Writes the field's value, `{field_var}`, to the register{array_index_comment}"
                    if len(register.fields) <= 1:
                        comment += " (single-field register)."
                    else:
                        comment += ", using default values for all other fields."
                    # Write the given field value with default values for all other fields
                    fields_code.append(f"""
{base_ind}/// {comment}
{base_ind}/// Returns an error description on failure.
{base_ind}pub fn write_{reg_name}_{field_name}(&mut self{array_args}, {field_var}: {field_type}) -> Result<(), &'static str> {{
{base_ind}{ind}let {reg_var} = self.get_{reg_name}_default();
{base_ind}{ind}let new_{reg_var} = self.set_{reg_name}_{field_name}_in({reg_var}, {field_var})?;
{base_ind}{ind}self.write_{reg_name}({array_index_param_set}new_{reg_var})
{base_ind}}}
""")

        # Now create `register_code` to produce end result
        register_code: list[str] = []
        register_code.append(self._newline())
        register_code.append(
            self._get_comment_header(
                f"Register{reg_array_txt} `{reg_name}` ({mode_str})"
                + register_description,
                base_ind_lev,
            )
        )
        register_code.append(self._newline())

        # Register default value
        register_code.append(f"""
{base_ind}/// Returns the register's default raw value.
{base_ind}pub fn get_{reg_name}_default(&self) -> u32 {{
{base_ind}{ind}0x{reg_default_value:X}u32
{base_ind}}}
""")
        # Register getter (raw)
        if is_read:
            # Register getter (raw u32)
            register_code.append(f"""
{base_ind}/// Reads the register{array_index_comment} and returns its raw value (without field validity checks),
{base_ind}/// or an error description on failure.
{base_ind}pub fn read_{reg_name}(&self{array_args}) -> Result<u32, &'static str> {{
{array_check}\
{base_ind}{ind}self.accessor.read32({offset_expr})
{base_ind}}}
""")

        # Register setter (raw)
        if is_write:
            # Register setter (raw u32)
            register_code.append(f"""
{base_ind}/// Writes the raw value in `reg_val` to the register{array_index_comment} (without field validity checks).
{base_ind}/// Returns an error description on failure.
{base_ind}pub fn write_{reg_name}(&mut self{array_args}, {reg_var}: u32) -> Result<(), &'static str> {{
{array_check}\
{base_ind}{ind}self.accessor.write32({offset_expr}, {reg_var})
{base_ind}}}
""")

        # Methods for fields
        register_code.extend(fields_code)

        # Done
        return "".join(register_code)
